// Code generated by github.com/soven/go-iterate. DO NOT EDIT.
package iter

import "github.com/pkg/errors"

// StringConverter is an object converting an item type of string.
type StringConverter interface {
	// Convert should convert an item type of string into another item of string.
	// It is suggested to return EndOfStringIterator to stop iteration.
	Convert(string) (string, error)
}

// StringConvert is a shortcut implementation
// of StringConverter based on a function.
type StringConvert func(string) (string, error)

// Convert converts an item type of string into another item of string.
// It is suggested to return EndOfStringIterator to stop iteration.
func (c StringConvert) Convert(item string) (string, error) { return c(item) }

// NoStringConvert does nothing with item, just returns it as is.
var NoStringConvert StringConverter = StringConvert(
	func(item string) (string, error) { return item, nil })

type doubleStringConverter struct {
	lhs, rhs StringConverter
}

func (c doubleStringConverter) Convert(item string) (string, error) {
	item, err := c.lhs.Convert(item)
	if err != nil {
		return "", errors.Wrap(err, "convert lhs")
	}
	item, err = c.rhs.Convert(item)
	if err != nil {
		return "", errors.Wrap(err, "convert rhs")
	}
	return item, nil
}

// StringConverterSeries combines all the given converters to sequenced one
// It returns no converter if the list of converters is empty.
func StringConverterSeries(converters ...StringConverter) StringConverter {
	var series StringConverter = NoStringConvert
	for i := len(converters) - 1; i >= 0; i-- {
		if converters[i] == nil {
			continue
		}
		series = doubleStringConverter{lhs: converters[i], rhs: series}
	}

	return series
}

// ConvertingStringIterator does iteration with
// converting by previously set converter.
type ConvertingStringIterator struct {
	preparedStringItem
	converter StringConverter
}

// HasNext checks if there is the next item
// in the iterator. HasNext is idempotent.
func (it *ConvertingStringIterator) HasNext() bool {
	if it.hasNext {
		return true
	}
	if it.preparedStringItem.HasNext() {
		next := it.base.Next()
		next, err := it.converter.Convert(next)
		if err != nil {
			if !isEndOfStringIterator(err) {
				err = errors.Wrap(err, "filtering iterator: check")
			}
			it.err = err
			return false
		}

		it.hasNext = true
		it.next = next
		return true
	}

	return false
}

// StringConverting sets converter while iterating over items.
// If converters is empty, so all items will not be affected.
func StringConverting(items StringIterator, converters ...StringConverter) StringIterator {
	if items == nil {
		return EmptyStringIterator
	}
	return &ConvertingStringIterator{
		preparedStringItem{base: items}, StringConverterSeries(converters...)}
}
