package iter

// Code generated by github.com/soven/go-iterate. DO NOT EDIT.
import "github.com/pkg/errors"

type Converter interface {
	// It is suggested to return EndOfIterator to stop iteration.
	Convert(interface{}) (interface{}, error)
}

type Convert func(interface{}) (interface{}, error)

func (c Convert) Convert(item interface{}) (interface{}, error) { return c(item) }

var NoConvert = Convert(func(item interface{}) (interface{}, error) { return item, nil })

type doubleConverter struct {
	lhs, rhs Converter
}

func (c doubleConverter) Convert(item interface{}) (interface{}, error) {
	item, err := c.lhs.Convert(item)
	if err != nil {
		return nil, errors.Wrap(err, "convert lhs")
	}
	item, err = c.rhs.Convert(item)
	if err != nil {
		return nil, errors.Wrap(err, "convert rhs")
	}
	return item, nil
}

func ConverterSeries(converters ...Converter) Converter {
	var series Converter = NoConvert
	for i := len(converters) - 1; i >= 0; i-- {
		if converters[i] == nil {
			continue
		}
		series = doubleConverter{lhs: converters[i], rhs: series}
	}

	return series
}

type ConvertingIterator struct {
	preparedItem
	converter Converter
}

func (it *ConvertingIterator) HasNext() bool {
	if it.hasNext {
		return true
	}
	if it.preparedItem.HasNext() {
		next := it.base.Next()
		next, err := it.converter.Convert(next)
		if err != nil {
			if !isEndOfIterator(err) {
				err = errors.Wrap(err, "filtering iterator: check")
			}
			it.err = err
			return false
		}

		it.hasNext = true
		it.next = next
		return true
	}

	return false
}

// Converting sets converter while iterating over items.
// If converters is empty, so all items will not be affected.
func Converting(items Iterator, converters ...Converter) Iterator {
	if items == nil {
		return EmptyIterator
	}
	return &ConvertingIterator{preparedItem{base: items}, ConverterSeries(converters...)}
}

func Map(items Iterator, converter ...Converter) error {
	// no error wrapping since no additional context for the error; just return it.
	return Discard(Converting(items, converter...))
}
