// Code generated by github.com/soven/go-iterate. DO NOT EDIT.
package iter

// Int32Iterator is an iterator over items type of int32.
type Int32Iterator interface {
	// HasNext checks if there is the next item
	// in the iterator. HasNext should be idempotent.
	HasNext() bool
	// Next should return next item in the iterator.
	// It should be invoked after check HasNext.
	Next() int32
	// Err contains first met error while Next.
	Err() error
}

type emptyInt32Iterator struct{}

func (emptyInt32Iterator) HasNext() bool      { return false }
func (emptyInt32Iterator) Next() (next int32) { return 0 }
func (emptyInt32Iterator) Err() error         { return nil }

// EmptyInt32Iterator is a zero value for Int32Iterator.
// It is not contains any item to iterate over it.
var EmptyInt32Iterator Int32Iterator = emptyInt32Iterator{}

// Int32IterMaker is a maker of Int32Iterator.
type Int32IterMaker interface {
	// MakeIter should return a new instance of Int32Iterator to iterate over it.
	// It is suggested to return EmptyInt32Iterator if the error is not nil.
	MakeIter() (Int32Iterator, error)
}

// MakeInt32Iter is a shortcut implementation
// of Int32Iterator based on a function.
type MakeInt32Iter func() (Int32Iterator, error)

// MakeIter returns a new instance of Int32Iterator to iterate over it.
// It returns EmptyInt32Iterator if the error is not nil.
func (m MakeInt32Iter) MakeIter() (Int32Iterator, error) { return m() }

// MakeNoInt32Iter is a zero value for Int32IterMaker.
// It always returns EmptyInt32Iterator and an empty error.
var MakeNoInt32Iter Int32IterMaker = MakeInt32Iter(
	func() (Int32Iterator, error) { return EmptyInt32Iterator, nil })

// Int32Discard just range over all items and do nothing with each of them.
func Int32Discard(items Int32Iterator) error {
	if items == nil {
		return nil
	}
	for items.HasNext() {
		_ = items.Next()
	}
	// no error wrapping since no additional context for the error; just return it.
	return items.Err()
}
