package iter

// Code generated by github.com/soven/go-iterate. DO NOT EDIT.
import "github.com/pkg/errors"

type IntConverter interface {
	// It is suggested to return EndOfIntIterator to stop iteration.
	Convert(int) (int, error)
}

type IntConvert func(int) (int, error)

func (c IntConvert) Convert(item int) (int, error) { return c(item) }

var NoIntConvert = IntConvert(func(item int) (int, error) { return item, nil })

type doubleIntConverter struct {
	lhs, rhs IntConverter
}

func (c doubleIntConverter) Convert(item int) (int, error) {
	item, err := c.lhs.Convert(item)
	if err != nil {
		return 0, errors.Wrap(err, "convert lhs")
	}
	item, err = c.rhs.Convert(item)
	if err != nil {
		return 0, errors.Wrap(err, "convert rhs")
	}
	return item, nil
}

func IntConverterSeries(converters ...IntConverter) IntConverter {
	var series IntConverter = NoIntConvert
	for i := len(converters) - 1; i >= 0; i-- {
		if converters[i] == nil {
			continue
		}
		series = doubleIntConverter{lhs: converters[i], rhs: series}
	}

	return series
}

type ConvertingIntIterator struct {
	preparedIntItem
	converter IntConverter
}

func (it *ConvertingIntIterator) HasNext() bool {
	if it.hasNext {
		return true
	}
	if it.preparedIntItem.HasNext() {
		next := it.base.Next()
		next, err := it.converter.Convert(next)
		if err != nil {
			if !isEndOfIntIterator(err) {
				err = errors.Wrap(err, "filtering iterator: check")
			}
			it.err = err
			return false
		}

		it.hasNext = true
		it.next = next
		return true
	}

	return false
}

// IntConverting sets converter while iterating over items.
// If converters is empty, so all items will not be affected.
func IntConverting(items IntIterator, converters ...IntConverter) IntIterator {
	if items == nil {
		return EmptyIntIterator
	}
	return &ConvertingIntIterator{preparedIntItem{base: items}, IntConverterSeries(converters...)}
}

func IntMap(items IntIterator, converter ...IntConverter) error {
	// no error wrapping since no additional context for the error; just return it.
	return IntDiscard(IntConverting(items, converter...))
}
