package iter

// Code generated by github.com/soven/go-iterate. DO NOT EDIT.
import "github.com/pkg/errors"

type Uint8Converter interface {
	// It is suggested to return EndOfUint8Iterator to stop iteration.
	Convert(uint8) (uint8, error)
}

type Uint8Convert func(uint8) (uint8, error)

func (c Uint8Convert) Convert(item uint8) (uint8, error) { return c(item) }

var NoUint8Convert = Uint8Convert(func(item uint8) (uint8, error) { return item, nil })

type doubleUint8Converter struct {
	lhs, rhs Uint8Converter
}

func (c doubleUint8Converter) Convert(item uint8) (uint8, error) {
	item, err := c.lhs.Convert(item)
	if err != nil {
		return 0, errors.Wrap(err, "convert lhs")
	}
	item, err = c.rhs.Convert(item)
	if err != nil {
		return 0, errors.Wrap(err, "convert rhs")
	}
	return item, nil
}

func Uint8ConverterSeries(converters ...Uint8Converter) Uint8Converter {
	var series Uint8Converter = NoUint8Convert
	for i := len(converters) - 1; i >= 0; i-- {
		if converters[i] == nil {
			continue
		}
		series = doubleUint8Converter{lhs: converters[i], rhs: series}
	}

	return series
}

type ConvertingUint8Iterator struct {
	preparedUint8Item
	converter Uint8Converter
}

func (it *ConvertingUint8Iterator) HasNext() bool {
	if it.hasNext {
		return true
	}
	if it.preparedUint8Item.HasNext() {
		next := it.base.Next()
		next, err := it.converter.Convert(next)
		if err != nil {
			if !isEndOfUint8Iterator(err) {
				err = errors.Wrap(err, "filtering iterator: check")
			}
			it.err = err
			return false
		}

		it.hasNext = true
		it.next = next
		return true
	}

	return false
}

// Uint8Converting sets converter while iterating over items.
// If converters is empty, so all items will not be affected.
func Uint8Converting(items Uint8Iterator, converters ...Uint8Converter) Uint8Iterator {
	if items == nil {
		return EmptyUint8Iterator
	}
	return &ConvertingUint8Iterator{preparedUint8Item{base: items}, Uint8ConverterSeries(converters...)}
}

func Uint8Map(items Uint8Iterator, converter ...Uint8Converter) error {
	// no error wrapping since no additional context for the error; just return it.
	return Uint8Discard(Uint8Converting(items, converter...))
}
