// Code generated by github.com/soven/go-iterate. DO NOT EDIT.
package iter

import "github.com/pkg/errors"

// Int32Handler is an object handling an item type of int32.
type Int32Handler interface {
	// Handle should do something with item of int32.
	// It is suggested to return EndOfInt32Iterator to stop iteration.
	Handle(int32) error
}

// Int32Handle is a shortcut implementation
// of Int32Handler based on a function.
type Int32Handle func(int32) error

// Handle does something with item of int32.
// It is suggested to return EndOfInt32Iterator to stop iteration.
func (h Int32Handle) Handle(item int32) error { return h(item) }

// Int32DoNothing does nothing.
var Int32DoNothing Int32Handler = Int32Handle(func(_ int32) error { return nil })

type doubleInt32Handler struct {
	lhs, rhs Int32Handler
}

func (h doubleInt32Handler) Handle(item int32) error {
	err := h.lhs.Handle(item)
	if err != nil {
		return errors.Wrap(err, "handle lhs")
	}
	err = h.rhs.Handle(item)
	if err != nil {
		return errors.Wrap(err, "handle rhs")
	}
	return nil
}

// Int32HandlerSeries combines all the given handlers to sequenced one
// It returns do nothing handler if the list of handlers is empty.
func Int32HandlerSeries(handlers ...Int32Handler) Int32Handler {
	var series = Int32DoNothing
	for i := len(handlers) - 1; i >= 0; i-- {
		if handlers[i] == nil {
			continue
		}
		series = doubleInt32Handler{lhs: handlers[i], rhs: series}
	}
	return series
}

// HandlingInt32Iterator does iteration with
// handling by previously set handler.
type HandlingInt32Iterator struct {
	preparedInt32Item
	handler Int32Handler
}

// HasNext checks if there is the next item
// in the iterator. HasNext is idempotent.
func (it *HandlingInt32Iterator) HasNext() bool {
	if it.hasNext {
		return true
	}
	if it.preparedInt32Item.HasNext() {
		next := it.base.Next()
		err := it.handler.Handle(next)
		if err != nil {
			if !isEndOfInt32Iterator(err) {
				err = errors.Wrap(err, "handling iterator: check")
			}
			it.err = err
			return false
		}

		it.hasNext = true
		it.next = next
		return true
	}

	return false
}

// Int32Handling sets handler while iterating over items.
// If handlers is empty, so it will do nothing.
func Int32Handling(items Int32Iterator, handlers ...Int32Handler) Int32Iterator {
	if items == nil {
		return EmptyInt32Iterator
	}
	return &HandlingInt32Iterator{
		preparedInt32Item{base: items}, Int32HandlerSeries(handlers...)}
}

// Int32EnumHandler is an object handling an item type of int32 and its ordered number.
type Int32EnumHandler interface {
	// Handle should do something with item of int32 and its ordered number.
	// It is suggested to return EndOfInt32Iterator to stop iteration.
	Handle(int, int32) error
}

// Int32EnumHandle is a shortcut implementation
// of Int32EnumHandler based on a function.
type Int32EnumHandle func(int, int32) error

// Handle does something with item of int32 and its ordered number.
// It is suggested to return EndOfInt32Iterator to stop iteration.
func (h Int32EnumHandle) Handle(n int, item int32) error { return h(n, item) }

// Int32DoEnumNothing does nothing.
var Int32DoEnumNothing = Int32EnumHandle(func(_ int, _ int32) error { return nil })

type doubleInt32EnumHandler struct {
	lhs, rhs Int32EnumHandler
}

func (h doubleInt32EnumHandler) Handle(n int, item int32) error {
	err := h.lhs.Handle(n, item)
	if err != nil {
		return errors.Wrap(err, "handle lhs")
	}
	err = h.rhs.Handle(n, item)
	if err != nil {
		return errors.Wrap(err, "handle rhs")
	}
	return nil
}

// Int32EnumHandlerSeries combines all the given handlers to sequenced one
// It returns do nothing handler if the list of handlers is empty.
func Int32EnumHandlerSeries(handlers ...Int32EnumHandler) Int32EnumHandler {
	var series Int32EnumHandler = Int32DoEnumNothing
	for i := len(handlers) - 1; i >= 0; i-- {
		if handlers[i] == nil {
			continue
		}
		series = doubleInt32EnumHandler{lhs: handlers[i], rhs: series}
	}
	return series
}

// EnumHandlingInt32Iterator does iteration with
// handling by previously set handler.
type EnumHandlingInt32Iterator struct {
	preparedInt32Item
	handler Int32EnumHandler
	count   int
}

// HasNext checks if there is the next item
// in the iterator. HasNext is idempotent.
func (it *EnumHandlingInt32Iterator) HasNext() bool {
	if it.hasNext {
		return true
	}
	if it.preparedInt32Item.HasNext() {
		next := it.base.Next()
		err := it.handler.Handle(it.count, next)
		if err != nil {
			if !isEndOfInt32Iterator(err) {
				err = errors.Wrap(err, "enum handling iterator: check")
			}
			it.err = err
			return false
		}
		it.count++

		it.hasNext = true
		it.next = next
		return true
	}

	return false
}

// Int32EnumHandling sets handler while iterating over items with their serial number.
// If handlers is empty, so it will do nothing.
func Int32EnumHandling(items Int32Iterator, handlers ...Int32EnumHandler) Int32Iterator {
	if items == nil {
		return EmptyInt32Iterator
	}
	return &EnumHandlingInt32Iterator{
		preparedInt32Item{base: items}, Int32EnumHandlerSeries(handlers...), 0}
}
