// Code generated by github.com/soven/go-iterate. DO NOT EDIT.
package iter

import "github.com/pkg/errors"

type Uint16Handler interface {
	// It is suggested to return EndOfUint16Iterator to stop iteration.
	Handle(uint16) error
}

type Uint16Handle func(uint16) error

func (h Uint16Handle) Handle(item uint16) error { return h(item) }

var Uint16DoNothing = Uint16Handle(func(_ uint16) error { return nil })

type doubleUint16Handler struct {
	lhs, rhs Uint16Handler
}

func (h doubleUint16Handler) Handle(item uint16) error {
	err := h.lhs.Handle(item)
	if err != nil {
		return errors.Wrap(err, "handle lhs")
	}
	err = h.rhs.Handle(item)
	if err != nil {
		return errors.Wrap(err, "handle rhs")
	}
	return nil
}

func Uint16HandlerSeries(handlers ...Uint16Handler) Uint16Handler {
	var series Uint16Handler = Uint16DoNothing
	for i := len(handlers) - 1; i >= 0; i-- {
		if handlers[i] == nil {
			continue
		}
		series = doubleUint16Handler{lhs: handlers[i], rhs: series}
	}
	return series
}

type HandlingUint16Iterator struct {
	preparedUint16Item
	handler Uint16Handler
}

func (it *HandlingUint16Iterator) HasNext() bool {
	if it.hasNext {
		return true
	}
	if it.preparedUint16Item.HasNext() {
		next := it.base.Next()
		err := it.handler.Handle(next)
		if err != nil {
			if !isEndOfUint16Iterator(err) {
				err = errors.Wrap(err, "handling iterator: check")
			}
			it.err = err
			return false
		}

		it.hasNext = true
		it.next = next
		return true
	}

	return false
}

// Uint16Handling sets handler while iterating over items.
// If handlers is empty, so it will do nothing.
func Uint16Handling(items Uint16Iterator, handlers ...Uint16Handler) Uint16Iterator {
	if items == nil {
		return EmptyUint16Iterator
	}
	return &HandlingUint16Iterator{preparedUint16Item{base: items}, Uint16HandlerSeries(handlers...)}
}

func Uint16Range(items Uint16Iterator, handler ...Uint16Handler) error {
	// no error wrapping since no additional context for the error; just return it.
	return Uint16Discard(Uint16Handling(items, handler...))
}

type Uint16EnumHandler interface {
	// It is suggested to return EndOfUint16Iterator to stop iteration.
	Handle(int, uint16) error
}

type Uint16EnumHandle func(int, uint16) error

func (h Uint16EnumHandle) Handle(n int, item uint16) error { return h(n, item) }

var Uint16DoEnumNothing = Uint16EnumHandle(func(_ int, _ uint16) error { return nil })

type doubleUint16EnumHandler struct {
	lhs, rhs Uint16EnumHandler
}

func (h doubleUint16EnumHandler) Handle(n int, item uint16) error {
	err := h.lhs.Handle(n, item)
	if err != nil {
		return errors.Wrap(err, "handle lhs")
	}
	err = h.rhs.Handle(n, item)
	if err != nil {
		return errors.Wrap(err, "handle rhs")
	}
	return nil
}

func Uint16EnumHandlerSeries(handlers ...Uint16EnumHandler) Uint16EnumHandler {
	var series Uint16EnumHandler = Uint16DoEnumNothing
	for i := len(handlers) - 1; i >= 0; i-- {
		if handlers[i] == nil {
			continue
		}
		series = doubleUint16EnumHandler{lhs: handlers[i], rhs: series}
	}
	return series
}

type EnumHandlingUint16Iterator struct {
	preparedUint16Item
	handler Uint16EnumHandler
	count   int
}

func (it *EnumHandlingUint16Iterator) HasNext() bool {
	if it.hasNext {
		return true
	}
	if it.preparedUint16Item.HasNext() {
		next := it.base.Next()
		err := it.handler.Handle(it.count, next)
		if err != nil {
			if !isEndOfUint16Iterator(err) {
				err = errors.Wrap(err, "enum handling iterator: check")
			}
			it.err = err
			return false
		}
		it.count++

		it.hasNext = true
		it.next = next
		return true
	}

	return false
}

// Uint16EnumHandling sets handler while iterating over items with their serial number.
// If handlers is empty, so it will do nothing.
func Uint16EnumHandling(items Uint16Iterator, handlers ...Uint16EnumHandler) Uint16Iterator {
	if items == nil {
		return EmptyUint16Iterator
	}
	return &EnumHandlingUint16Iterator{
		preparedUint16Item{base: items}, Uint16EnumHandlerSeries(handlers...), 0}
}

func Uint16Enumerate(items Uint16Iterator, handler ...Uint16EnumHandler) error {
	// no error wrapping since no additional context for the error; just return it.
	return Uint16Discard(Uint16EnumHandling(items, handler...))
}
