// Code generated by github.com/soven/go-iterate. DO NOT EDIT.
package iter

// ByteIterator is an iterator over items type of byte.
type ByteIterator interface {
	// HasNext checks if there is the next item
	// in the iterator. HasNext should be idempotent.
	HasNext() bool
	// Next should return next item in the iterator.
	// It should be invoked after check HasNext.
	Next() byte
	// Err contains first met error while Next.
	Err() error
}

type emptyByteIterator struct{}

func (emptyByteIterator) HasNext() bool     { return false }
func (emptyByteIterator) Next() (next byte) { return 0 }
func (emptyByteIterator) Err() error        { return nil }

// EmptyByteIterator is a zero value for ByteIterator.
// It is not contains any item to iterate over it.
var EmptyByteIterator ByteIterator = emptyByteIterator{}

// ByteIterMaker is a maker of ByteIterator.
type ByteIterMaker interface {
	// MakeIter should return a new instance of ByteIterator to iterate over it.
	// It is suggested to return EmptyByteIterator if the error is not nil.
	MakeIter() (ByteIterator, error)
}

// MakeByteIter is a shortcut implementation
// of ByteIterator based on a function.
type MakeByteIter func() (ByteIterator, error)

// MakeIter returns a new instance of ByteIterator to iterate over it.
// It returns EmptyByteIterator if the error is not nil.
func (m MakeByteIter) MakeIter() (ByteIterator, error) { return m() }

// MakeNoByteIter is a zero value for ByteIterMaker.
// It always returns EmptyByteIterator and an empty error.
var MakeNoByteIter ByteIterMaker = MakeByteIter(
	func() (ByteIterator, error) { return EmptyByteIterator, nil })

// ByteDiscard just range over all items and do nothing with each of them.
func ByteDiscard(items ByteIterator) error {
	if items == nil {
		return nil
	}
	for items.HasNext() {
		_ = items.Next()
	}
	// no error wrapping since no additional context for the error; just return it.
	return items.Err()
}
