package iter

// Code generated by github.com/soven/go-iterate. DO NOT EDIT.
import "github.com/pkg/errors"

type Uint32Converter interface {
	// It is suggested to return EndOfUint32Iterator to stop iteration.
	Convert(uint32) (uint32, error)
}

type Uint32Convert func(uint32) (uint32, error)

func (c Uint32Convert) Convert(item uint32) (uint32, error) { return c(item) }

var NoUint32Convert = Uint32Convert(func(item uint32) (uint32, error) { return item, nil })

type doubleUint32Converter struct {
	lhs, rhs Uint32Converter
}

func (c doubleUint32Converter) Convert(item uint32) (uint32, error) {
	item, err := c.lhs.Convert(item)
	if err != nil {
		return 0, errors.Wrap(err, "convert lhs")
	}
	item, err = c.rhs.Convert(item)
	if err != nil {
		return 0, errors.Wrap(err, "convert rhs")
	}
	return item, nil
}

func Uint32ConverterSeries(converters ...Uint32Converter) Uint32Converter {
	var series Uint32Converter = NoUint32Convert
	for i := len(converters) - 1; i >= 0; i-- {
		if converters[i] == nil {
			continue
		}
		series = doubleUint32Converter{lhs: converters[i], rhs: series}
	}

	return series
}

type ConvertingUint32Iterator struct {
	preparedUint32Item
	converter Uint32Converter
}

func (it *ConvertingUint32Iterator) HasNext() bool {
	if it.hasNext {
		return true
	}
	if it.preparedUint32Item.HasNext() {
		next := it.base.Next()
		next, err := it.converter.Convert(next)
		if err != nil {
			if !isEndOfUint32Iterator(err) {
				err = errors.Wrap(err, "filtering iterator: check")
			}
			it.err = err
			return false
		}

		it.hasNext = true
		it.next = next
		return true
	}

	return false
}

// Uint32Converting sets converter while iterating over items.
// If converters is empty, so all items will not be affected.
func Uint32Converting(items Uint32Iterator, converters ...Uint32Converter) Uint32Iterator {
	if items == nil {
		return EmptyUint32Iterator
	}
	return &ConvertingUint32Iterator{preparedUint32Item{base: items}, Uint32ConverterSeries(converters...)}
}

func Uint32Map(items Uint32Iterator, converter ...Uint32Converter) error {
	// no error wrapping since no additional context for the error; just return it.
	return Uint32Discard(Uint32Converting(items, converter...))
}
