// Code generated by github.com/soven/go-iterate. DO NOT EDIT.
package iter

type Uint8Iterator interface {
	// HasNext checks if there is the next item
	// in the iterator. HasNext should be idempotent.
	HasNext() bool
	// Next should be invoked after check HasNext.
	Next() uint8
	// Err contains first met error while Next.
	Err() error
}

type emptyUint8Iterator struct{}

func (emptyUint8Iterator) HasNext() bool      { return false }
func (emptyUint8Iterator) Next() (next uint8) { return 0 }
func (emptyUint8Iterator) Err() error         { return nil }

var EmptyUint8Iterator = emptyUint8Iterator{}

type Uint8IterMaker interface {
	MakeIter() (Uint8Iterator, error)
}

type MakeUint8Iter func() (Uint8Iterator, error)

func (m MakeUint8Iter) MakeIter() (Uint8Iterator, error) { return m() }

var MakeNoUint8Iter = MakeUint8Iter(func() (Uint8Iterator, error) { return EmptyUint8Iterator, nil })

// Uint8Discard just range over all items and do nothing with each of them.
func Uint8Discard(items Uint8Iterator) error {
	if items == nil {
		return nil
	}
	for items.HasNext() {
		_ = items.Next()
	}
	// no error wrapping since no additional context for the error; just return it.
	return items.Err()
}
