// Code generated by github.com/soven/go-iterate. DO NOT EDIT.
package iter

import "github.com/pkg/errors"

type Uint16Checker interface {
	// It is suggested to return EndOfUint16Iterator to stop iteration.
	Check(uint16) (bool, error)
}

type Uint16Check func(uint16) (bool, error)

func (ch Uint16Check) Check(item uint16) (bool, error) { return ch(item) }

var (
	AlwaysUint16CheckTrue  = Uint16Check(func(item uint16) (bool, error) { return true, nil })
	AlwaysUint16CheckFalse = Uint16Check(func(item uint16) (bool, error) { return false, nil })
)

func NotUint16(checker Uint16Checker) Uint16Checker {
	if checker == nil {
		return AlwaysUint16CheckTrue
	}
	return Uint16Check(func(item uint16) (bool, error) {
		yes, err := checker.Check(item)
		if err != nil {
			// No error wrapping since an error context is missing.
			return false, err
		}

		return !yes, nil
	})
}

type andUint16 struct {
	lhs, rhs Uint16Checker
}

func (a andUint16) Check(item uint16) (bool, error) {
	isLHSPassed, err := a.lhs.Check(item)
	if err != nil {
		return false, wrapIfNotEndOfUint16Iterator(err, "lhs check")
	}
	if !isLHSPassed {
		return false, nil
	}

	isRHSPassed, err := a.rhs.Check(item)
	if err != nil {
		return false, wrapIfNotEndOfUint16Iterator(err, "rhs check")
	}
	return isRHSPassed, nil
}

func AllUint16(checkers ...Uint16Checker) Uint16Checker {
	var all Uint16Checker = AlwaysUint16CheckTrue
	for i := len(checkers) - 1; i >= 0; i-- {
		if checkers[i] == nil {
			continue
		}
		all = andUint16{checkers[i], all}
	}
	return all
}

type orUint16 struct {
	lhs, rhs Uint16Checker
}

func (o orUint16) Check(item uint16) (bool, error) {
	isLHSPassed, err := o.lhs.Check(item)
	if err != nil {
		return false, wrapIfNotEndOfUint16Iterator(err, "lhs check")
	}
	if isLHSPassed {
		return true, nil
	}

	isRHSPassed, err := o.rhs.Check(item)
	if err != nil {
		return false, wrapIfNotEndOfUint16Iterator(err, "rhs check")
	}
	return isRHSPassed, nil
}

func AnyUint16(checkers ...Uint16Checker) Uint16Checker {
	var any Uint16Checker = AlwaysUint16CheckFalse
	for i := len(checkers) - 1; i >= 0; i-- {
		if checkers[i] == nil {
			continue
		}
		any = orUint16{checkers[i], any}
	}
	return any
}

type FilteringUint16Iterator struct {
	preparedUint16Item
	filter Uint16Checker
}

func (it *FilteringUint16Iterator) HasNext() bool {
	if it.hasNext {
		return true
	}
	for it.preparedUint16Item.HasNext() {
		next := it.base.Next()
		isFilterPassed, err := it.filter.Check(next)
		if err != nil {
			if !isEndOfUint16Iterator(err) {
				err = errors.Wrap(err, "filtering iterator: check")
			}
			it.err = err
			return false
		}

		if !isFilterPassed {
			continue
		}

		it.hasNext = true
		it.next = next
		return true
	}

	return false
}

// Uint16Filtering sets filter while iterating over items.
// If filters is empty, so all items will return.
func Uint16Filtering(items Uint16Iterator, filters ...Uint16Checker) Uint16Iterator {
	if items == nil {
		return EmptyUint16Iterator
	}
	return &FilteringUint16Iterator{preparedUint16Item{base: items}, AllUint16(filters...)}
}

func Uint16Filter(items Uint16Iterator, checker ...Uint16Checker) error {
	// no error wrapping since no additional context for the error; just return it.
	return Uint16Discard(Uint16Filtering(items, checker...))
}

type Uint16EnumChecker interface {
	// It is suggested to return EndOfUint16Iterator to stop iteration.
	Check(int, uint16) (bool, error)
}

type Uint16EnumCheck func(int, uint16) (bool, error)

func (ch Uint16EnumCheck) Check(n int, item uint16) (bool, error) { return ch(n, item) }

type enumFromUint16Checker struct {
	Uint16Checker
}

func (ch enumFromUint16Checker) Check(_ int, item uint16) (bool, error) {
	return ch.Uint16Checker.Check(item)
}

func EnumFromUint16Checker(checker Uint16Checker) Uint16EnumChecker {
	return &enumFromUint16Checker{checker}
}

var (
	AlwaysUint16EnumCheckTrue  = EnumFromUint16Checker(AlwaysUint16CheckTrue)
	AlwaysUint16EnumCheckFalse = EnumFromUint16Checker(AlwaysUint16CheckFalse)
)

func EnumNotUint16(checker Uint16EnumChecker) Uint16EnumChecker {
	if checker == nil {
		return AlwaysUint16EnumCheckTrue
	}
	return Uint16EnumCheck(func(n int, item uint16) (bool, error) {
		yes, err := checker.Check(n, item)
		if err != nil {
			// No error wrapping since an error context is missing.
			return false, err
		}

		return !yes, nil
	})
}

type enumAndUint16 struct {
	lhs, rhs Uint16EnumChecker
}

func (a enumAndUint16) Check(n int, item uint16) (bool, error) {
	isLHSPassed, err := a.lhs.Check(n, item)
	if err != nil {
		return false, wrapIfNotEndOfUint16Iterator(err, "lhs check")
	}
	if !isLHSPassed {
		return false, nil
	}

	isRHSPassed, err := a.rhs.Check(n, item)
	if err != nil {
		return false, wrapIfNotEndOfUint16Iterator(err, "rhs check")
	}
	return isRHSPassed, nil
}

func EnumAllUint16(checkers ...Uint16EnumChecker) Uint16EnumChecker {
	var all Uint16EnumChecker = AlwaysUint16EnumCheckTrue
	for i := len(checkers) - 1; i >= 0; i-- {
		if checkers[i] == nil {
			continue
		}
		all = enumAndUint16{checkers[i], all}
	}
	return all
}

type enumOrUint16 struct {
	lhs, rhs Uint16EnumChecker
}

func (o enumOrUint16) Check(n int, item uint16) (bool, error) {
	isLHSPassed, err := o.lhs.Check(n, item)
	if err != nil {
		return false, wrapIfNotEndOfUint16Iterator(err, "lhs check")
	}
	if isLHSPassed {
		return true, nil
	}

	isRHSPassed, err := o.rhs.Check(n, item)
	if err != nil {
		return false, wrapIfNotEndOfUint16Iterator(err, "rhs check")
	}
	return isRHSPassed, nil
}

func EnumAnyUint16(checkers ...Uint16EnumChecker) Uint16EnumChecker {
	var any Uint16EnumChecker = AlwaysUint16EnumCheckFalse
	for i := len(checkers) - 1; i >= 0; i-- {
		if checkers[i] == nil {
			continue
		}
		any = enumOrUint16{checkers[i], any}
	}
	return any
}

type EnumFilteringUint16Iterator struct {
	preparedUint16Item
	filter Uint16EnumChecker
	count  int
}

func (it *EnumFilteringUint16Iterator) HasNext() bool {
	if it.hasNext {
		return true
	}
	for it.preparedUint16Item.HasNext() {
		next := it.base.Next()
		isFilterPassed, err := it.filter.Check(it.count, next)
		if err != nil {
			if !isEndOfUint16Iterator(err) {
				err = errors.Wrap(err, "enum filtering iterator: check")
			}
			it.err = err
			return false
		}
		it.count++

		if !isFilterPassed {
			continue
		}

		it.hasNext = true
		it.next = next
		return true
	}

	return false
}

// Uint16EnumFiltering sets filter while iterating over items and their serial numbers.
// If filters is empty, so all items will return.
func Uint16EnumFiltering(items Uint16Iterator, filters ...Uint16EnumChecker) Uint16Iterator {
	if items == nil {
		return EmptyUint16Iterator
	}
	return &EnumFilteringUint16Iterator{preparedUint16Item{base: items}, EnumAllUint16(filters...), 0}
}

type DoingUntilUint16Iterator struct {
	preparedUint16Item
	until Uint16Checker
}

func (it *DoingUntilUint16Iterator) HasNext() bool {
	if it.hasNext {
		return true
	}
	for it.preparedUint16Item.HasNext() {
		next := it.base.Next()
		isUntilPassed, err := it.until.Check(next)
		if err != nil {
			if !isEndOfUint16Iterator(err) {
				err = errors.Wrap(err, "doing until iterator: until")
			}
			it.err = err
			return false
		}

		if isUntilPassed {
			it.err = EndOfUint16Iterator
		}

		it.hasNext = true
		it.next = next
		return true
	}

	return false
}

// Uint16DoingUntil sets until checker while iterating over items.
// If untilList is empty, so all items returned as is.
func Uint16DoingUntil(items Uint16Iterator, untilList ...Uint16Checker) Uint16Iterator {
	if items == nil {
		return EmptyUint16Iterator
	}
	return &DoingUntilUint16Iterator{preparedUint16Item{base: items}, AllUint16(untilList...)}
}

func Uint16DoUntil(items Uint16Iterator, untilList ...Uint16Checker) error {
	// no error wrapping since no additional context for the error; just return it.
	return Uint16Discard(Uint16DoingUntil(items, untilList...))
}

// Uint16GettingBatch returns the next batch from items.
func Uint16GettingBatch(items Uint16Iterator, batchSize int) Uint16Iterator {
	if items == nil {
		return EmptyUint16Iterator
	}
	if batchSize == 0 {
		return items
	}

	size := 0
	return Uint16DoingUntil(items, Uint16Check(func(item uint16) (bool, error) {
		size++
		return size >= batchSize, nil
	}))
}
