package iter

// Code generated by github.com/soven/go-iterate. DO NOT EDIT.
import "github.com/pkg/errors"

type Int16Converter interface {
	// It is suggested to return EndOfInt16Iterator to stop iteration.
	Convert(int16) (int16, error)
}

type Int16Convert func(int16) (int16, error)

func (c Int16Convert) Convert(item int16) (int16, error) { return c(item) }

var NoInt16Convert = Int16Convert(func(item int16) (int16, error) { return item, nil })

type doubleInt16Converter struct {
	lhs, rhs Int16Converter
}

func (c doubleInt16Converter) Convert(item int16) (int16, error) {
	item, err := c.lhs.Convert(item)
	if err != nil {
		return 0, errors.Wrap(err, "convert lhs")
	}
	item, err = c.rhs.Convert(item)
	if err != nil {
		return 0, errors.Wrap(err, "convert rhs")
	}
	return item, nil
}

func Int16ConverterSeries(converters ...Int16Converter) Int16Converter {
	var series Int16Converter = NoInt16Convert
	for i := len(converters) - 1; i >= 0; i-- {
		if converters[i] == nil {
			continue
		}
		series = doubleInt16Converter{lhs: converters[i], rhs: series}
	}

	return series
}

type ConvertingInt16Iterator struct {
	preparedInt16Item
	converter Int16Converter
}

func (it *ConvertingInt16Iterator) HasNext() bool {
	if it.hasNext {
		return true
	}
	if it.preparedInt16Item.HasNext() {
		next := it.base.Next()
		next, err := it.converter.Convert(next)
		if err != nil {
			if !isEndOfInt16Iterator(err) {
				err = errors.Wrap(err, "filtering iterator: check")
			}
			it.err = err
			return false
		}

		it.hasNext = true
		it.next = next
		return true
	}

	return false
}

// Int16Converting sets converter while iterating over items.
// If converters is empty, so all items will not be affected.
func Int16Converting(items Int16Iterator, converters ...Int16Converter) Int16Iterator {
	if items == nil {
		return EmptyInt16Iterator
	}
	return &ConvertingInt16Iterator{preparedInt16Item{base: items}, Int16ConverterSeries(converters...)}
}

func Int16Map(items Int16Iterator, converter ...Int16Converter) error {
	// no error wrapping since no additional context for the error; just return it.
	return Int16Discard(Int16Converting(items, converter...))
}
