// Code generated by mockery v2.4.0. DO NOT EDIT.

package mocks

import (
	resembled "github.com/soven/go-iterate/internal/testground/resembled"
	mock "github.com/stretchr/testify/mock"
)

// PrefixEnumComparer is an autogenerated mock type for the PrefixEnumComparer type
type PrefixEnumComparer struct {
	mock.Mock
}

// IsLess provides a mock function with given fields: nLHS, lhs, nRHS, rhs
func (_m *PrefixEnumComparer) IsLess(nLHS int, lhs resembled.Type, nRHS int, rhs resembled.Type) bool {
	ret := _m.Called(nLHS, lhs, nRHS, rhs)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int, resembled.Type, int, resembled.Type) bool); ok {
		r0 = rf(nLHS, lhs, nRHS, rhs)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
