// Code generated by mockery v2.4.0. DO NOT EDIT.

package mocks

import (
	resembled "github.com/soven/go-iterate/internal/testground/resembled"
	mock "github.com/stretchr/testify/mock"
)

// PrefixComparer is an autogenerated mock type for the PrefixComparer type
type PrefixComparer struct {
	mock.Mock
}

// IsLess provides a mock function with given fields: lhs, rhs
func (_m *PrefixComparer) IsLess(lhs resembled.Type, rhs resembled.Type) bool {
	ret := _m.Called(lhs, rhs)

	var r0 bool
	if rf, ok := ret.Get(0).(func(resembled.Type, resembled.Type) bool); ok {
		r0 = rf(lhs, rhs)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
