// Code generated by mockery v2.4.0. DO NOT EDIT.

package mocks

import (
	resembled "github.com/soven/go-iterate/internal/testground/resembled"
	mock "github.com/stretchr/testify/mock"
)

// PrefixEnumConverter is an autogenerated mock type for the PrefixEnumConverter type
type PrefixEnumConverter struct {
	mock.Mock
}

// Convert provides a mock function with given fields: n, val
func (_m *PrefixEnumConverter) Convert(n int, val resembled.Type) (resembled.Type, error) {
	ret := _m.Called(n, val)

	var r0 resembled.Type
	if rf, ok := ret.Get(0).(func(int, resembled.Type) resembled.Type); ok {
		r0 = rf(n, val)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resembled.Type)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, resembled.Type) error); ok {
		r1 = rf(n, val)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
