// Code generated by mockery v2.4.0. DO NOT EDIT.

package mocks

import (
	resembled "github.com/soven/go-iterate/internal/testground/resembled"
	mock "github.com/stretchr/testify/mock"
)

// PrefixEnumHandler is an autogenerated mock type for the PrefixEnumHandler type
type PrefixEnumHandler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: _a0, _a1
func (_m *PrefixEnumHandler) Handle(_a0 int, _a1 resembled.Type) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, resembled.Type) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
