package adding

import (
	"io/ioutil"

	"github.com/pkg/errors"

	"github.com/soven/go-iterate/internal/app"
)

type GenerateIterPrefixAdder struct {
	decorated app.IterGenerator

	prefix string
}

func newAssembleTemplateAdder(decorated app.IterGenerator, prefix string) GenerateIterPrefixAdder {
	if decorated == nil {
		decorated = app.NoGenerateIter
	}
	return GenerateIterPrefixAdder{decorated: decorated, prefix: prefix}
}

// GenerateIter generates code using path to package and context.
func (a GenerateIterPrefixAdder) GenerateIter(packagePath string, ctx app.GenerateIterContext,
) (targetFilePaths []string, err error) {
	targetFilePaths, err = a.decorated.GenerateIter(packagePath, ctx)
	if err != nil {
		// no wrapping since no additional context
		return nil, err
	}

	for _, filePath := range targetFilePaths {
		err := a.addPrefixToFile(filePath)
		if err != nil {
			return nil, errors.Wrapf(err, "add prefix `%s` to file `%s`", a.prefix, filePath)
		}
	}

	return targetFilePaths, nil
}

func (a GenerateIterPrefixAdder) addPrefixToFile(filePath string) error {
	if len(a.prefix) == 0 {
		return nil
	}

	fileBytes, err := ioutil.ReadFile(filePath)
	if err != nil {
		return errors.Wrap(err, "read file")
	}

	result := append([]byte(a.prefix), fileBytes...)

	err = ioutil.WriteFile(filePath, result, 0664)
	if err != nil {
		return errors.Wrap(err, "write file")
	}

	return nil
}

// WithNoEditPrefixAdding decorates app.IterGenerator with adding prefix logic.
func WithNoEditPrefixAdding(decorated app.IterGenerator) GenerateIterPrefixAdder {
	const noEditPrefix = "// Code generated by github.com/soven/go-iterate. DO NOT EDIT.\n\n"
	return newAssembleTemplateAdder(decorated, noEditPrefix)
}
